### ISSUE TITLE
auto-focus

### ISSUE THREAD

**Issue by mb324-unikent** [thybag/quick-spot#18]
Hi @thybag 

A filter box automatically gets focus on the page, whereas we'd really like this to be an option. What would be the best way of fixing this?

https://github.com/thybag/quick-spot/blob/03a2d88b4484f0c8db47e23ae78e8111f3c70a1f/quickspot.js#L62

**Comment by thybag** [comment]
Have  added the ability to turn that off in 0.9.6

Just call as `qs.showAll(undefined,undefined,false);` (assuming you don't want to change the default filtering/sorts - can't remember where or not we do in the KentTheme stuff etc.

**Comment by mb324-unikent** [comment]
hey @thybag ! Thanks for sorting that out. Works fine (don't need any change to default filtering, we were just calling showAll().
